ET http://localhost:4004/odata/v4/catalog/
Authorization: Basic joe:
###
POST http://localhost:4004/odata/v4/catalog/CreateEmployee
Authorization: Basic suvendurout807@gmail.com:
Content-Type: application/json

{"f_name":"Hello","l_name":"cdfv","dept":"MCA", "email":"fg","position":"position","mob_no":""}
###
GET  http://localhost:4004/odata/v4/catalog/getAllEmployee()
Authorization: Basic suvendurout807@gmail.com:
Content-Type: application/json
###
POST http://localhost:4004/odata/v4/catalog/DeleteEmployee
Authorization: Basic joe:
Content-Type: application/json

{"ID":4}
###
POST http://localhost:4004/odata/v4/catalog/UpdateEmployee
Authorization: Basic joe:
Content-Type: application/json

{ "ID": 2, "f_name":"Suvendu Kumar", "l_name":"Rout", "dept":"MCA"}
###
GET  http://localhost:4004/odata/v4/catalog/countEmployees()
Authorization: Basic joe:
###
POST http://localhost:4004/odata/v4/catalog/triggeremail
Authorization: Basic joe:
Content-Type: application/json

{"ID": 2, "f_name":"Hello","l_name":"cdfv","dept":"MCA", "email":"suvendurout011@gmail.com","position":"position","mob_no":""}
###